- name: configuring mysql 
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.kondarao.online 
  tasks:

  - name: "installing pip mysql"
    ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9

  - name: installing mysql in server
    ansible.builtin.package:
      name: mysql-server
      state:  present

  - name: starting server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setting credentials to database
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
    ignore_errors: true
    register: mysqlinfo

  - name: print the mysqlinfo
    ansible.builtin.debug:
      msg: "{{mysqlinfo}}"

  - name: setup my sql password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
    when: mysqlinfo.failed is true